### ISSUE TITLE
realTime not working catching events.

### ISSUE THREAD

**Issue by luncht1me** [mean-expert-official/fireloop.io#68] opened 2017-03-26 01:43 UTC
I've turned on `"debug": true` in my component-config for `loopback-component-realtime`.

My base angular2 app it setup exactly like the docs at http://docs.fireloop.io/en/api/#Read-Data-Using-%E2%80%98change%E2%80%99-Event

```ts
import { Component } from '@angular/core';
import { BASE_URL, API_VERSION } from './shared/base.url'
import { LoopBackConfig } from './shared/sdk';
import { Nooner, AccessToken, FireLoopRef } from './shared/sdk/models';
import { NoonerApi, RealTime } from './shared/sdk/services';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

  private nooner: Nooner = new Nooner();
  private friendsRef: FireLoopRef<Nooner>;

  constructor(private realTime: RealTime) {
    LoopBackConfig.setBaseURL(BASE_URL);
    LoopBackConfig.setApiVersion(API_VERSION);

    this.realTime
      .onReady()
      .subscribe(() => {
        console.log("check")
        this.friendsRef = this.realTime.FireLoop.ref<Nooner>(Nooner)
        this.friendsRef.on('change', {
          limit: 10,
          order: 'id DESC',
          include: 'friends'
        }).subscribe((friends: Nooner[]) => console.log("EVNT - change", friends))
        this.friendsRef.on('value').subscribe((friends: Nooner[]) => {
          console.log("EVNT - value", friends)
        })
      }
      );

  }

upsert(): void {
    console.log("yolo");
    this.nooner.username = "asdf99";
    this.nooner.password = "asdf";
    this.nooner.email = "asdf@asdf99.com";
    this.nooner.location = {lat: 0, lng: 0};
    this.nooner.timezone = -8;
    console.log("??", this.nooner);
    this.friendsRef.create(this.nooner).subscribe((instance: Nooner) => console.log(instance));
  }
```

When the page first loads, I get the console logs with my data, but whenever I add a new one w/ the upsert() function, I do not get the event logs again, EVEN THOUGH the debug shows in the console events are being fires and caught.

```
@mean-expert/loopback-component-realtime: FireLoop starting create: Nooner: {"data":{"username":"asdf99","password":"asdf","email":"asdf@asdf99.com","location":{"lat":0,"lng":0},"timezone":-8},"parent":null}
Nooner: Before Save
@mean-expert/loopback-component-realtime: FireLoop value broadcasting
@mean-expert/loopback-component-realtime: FireLoop child_added broadcasting
@mean-expert/loopback-component-realtime: FireLoop change broadcasting
@mean-expert/loopback-component-realtime: FireLoop stats broadcasting
@mean-expert/loopback-component-realtime: FireLoop value broadcast request received: {"limit":100,"order":"id DESC"}
@mean-expert/loopback-component-realtime: FireLoop value broadcast request received: {"limit":100,"order":"id DESC"}
@mean-expert/loopback-component-realtime: FireLoop change broadcast request received: {"limit":10,"order":"id DESC","include":"friends"}
@mean-expert/loopback-component-realtime: FireLoop change broadcast request received: {"limit":10,"order":"id DESC","include":"friends"}
```

Here you can see my browser's console output. The instance gets logged from the create callback, but the event never gets fired again. I'm really going to want to use realtime data for my application:
https://gyazo.com/2d7afa4a92c001c24f4cf3a8d6ec81f4

.............. What's the matter? How can the events be caught the first time on registry, but then never fire even though they're caught by the server.

I REALLY want to use and love FireLoop, but it's been an insane pain to just get any of the base functionality from the documentation working.

**Comment by jonathan-casarrubias** [comment] 2017-03-26 02:21
@luncht1me I'm really sorry you are having this problems and a bad first impression, but the beta 2 dependency issue has been just fixed in beta 2.3.

Also I just tried and I'm not having your problems on a basic test, even though we also have complex applications running on fireloop already.

After a clean installation of fireloop, I just created a Todo model with a text property and the following example worked right away.

````js
import { Component } from '@angular/core';
import { Todo, FireLoopRef } from './shared/sdk/models';
import { RealTime } from './shared/sdk/services';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app works!';
  todo: Todo = new Todo({
    text: 'hello world'
  });
  todoRef: FireLoopRef<Todo>;

  constructor(rt: RealTime) {
    rt.onReady().subscribe(() => {
      this.todoRef = rt.FireLoop.ref<Todo>(Todo);
      this.todoRef.on('change').subscribe((todos: Todo[]) => {
        console.log(todos);
      });
      this.todoRef.create(this.todo).subscribe();
    });
  }
}
````

Also there is a more complex example if you look at the starter being build by the community (WIP)

https://github.com/mean-expert-official/fireloop-starter

Anyway, I see on your logs that the client is actually requesting the updates for both value and change, not sure why the client is not receiving it back

IF you open the browser developer tools, within the network section you should be able to debug the websocket timeline, from there please verify if you are receiving the server's response.

Remember this platform is in beta, so we need a little of your patience and cooperation to keep detecting bugs and reporting these, we will address ASAP.

IF you want some extra help from the community I Can add you to the FireLoop slack channel, and we will be happy to help you.

PS. the value and change events will always fire on registration for a first time, and will keep firing subsequently. 

Cheers
Jon

**Comment by luncht1me** [comment] 2017-03-27 05:09
So, updated to beta2.3, and with this same setup, I can see that the websocket does pick up on the event, but it isn't parsed. I've copy/pasted the socket preview below. The data is there, but it's in a binary mess instead of coming through as an object. I'm assuming this is the cause of the event not being caught in angular and thus not console logging the change result.

`ÿ42["Nooner.value.result.577176371249509",{"location":{"lat":0,"lng":0},"score":0,"timezone":-8,"username":"Nooner3","email":"high@noon3.com","id":"58d89dc4fc53e219e453b340","createdAt":"2017-03-27T05:06:12.117Z","updatedAt":"2017-03-27T05:06:12.117Z"}]ÿ42["Nooner.value.broadcast.announce.577176371249509",1]ÿ42["Nooner.child_added.broadcast.announce.577176371249509",1]ÿ42["Nooner.change.broadcast.announce.577176371249509",1]ÿ42["Nooner.stats.broadcast.announce.577176371249509",1]`

**Comment by jonathan-casarrubias** [comment] 2017-03-27 13:30
Ok I've never seen that binary issue, it seems fun to debug, the problem is how to replicate though, because I don't think is a windows issue, there is a contributor that yesterday did test on windows and is working for him. so, I'll try to research in google for socket.io passing unexpected binaries.

At the end I pass a plain JSON from the server, so as you said the data is there, somehow it was corrupted but the original data was not, the first one..

Maybe I should json stringify before sending it..... Socket-io supposes to do that for us, but maybe delegating that to them is generating this issue

**Comment by brannon-darby** [comment] 2017-03-27 14:01
@luncht1me - if you can join our slack and/or create a repo that reproduces the issue, i'll be happy to look into this with you from a windows machine.

**Comment by luncht1me** [comment] 2017-03-27 16:24
Sure, send me a slack invite: lunchtime@nxtlvl.gg . I'll do what I can. @brannon-darby @jonathan-casarrubias .

I'll push up the whole repo from my home computer once I get home after work today for you guys to dl and try.

**Comment by jonathan-casarrubias** [comment] 2017-03-27 18:52
ok cool, just sent you an invite

**Comment by jonathan-casarrubias** [comment] 2017-05-03 19:41
@luncht1me is this issue still persisting? I don't see other guys having the same problem also I see some inactivity in here.

I will close this issue for now, let me know if it is persisting and you have a way to replicate the issue.

Regards
Jon

**Closed as completed by jonathan-casarrubias** 2017-05-03 19:41 UTC
