### ISSUE TITLE
Domain fireloop.io 

### ISSUE THREAD

**Issue by aleho70** [mean-expert-official/fireloop.io#121] opened 2017-09-24 19:24 UTC
Domain fireloop.io is not working, so what is the future of the project? Forget it and wait for Loopback 4?

**Comment by jonathan-casarrubias** [comment] 2017-09-25 19:57
Hey @aleho70 thanks for reaching out... The problems with the domain are now fixed.

About the project I can confirm that LB4 really affected the plans for this project, I have been following from the very beginning the LB4 development process and it is reaching to the point that the fireloop core modules could be developed on top of LB4.

LB4 might or not provide real-time functionalities, once the LB4 developer version is out I will be in the point to confirm if LB4 is enough or I need to rewrite FireLoop on top.

But as foundation they specifically told me that the intention is not to build everything their selves but to provide a framework where other platforms like FireLoop can be write on top.

One thing is definitive, old code and old projects will be deprecated in the near future in favor of new code and new projects.

Regards
Jon

**Comment by aleho70** [comment] 2017-09-26 08:56
Hi Jon,
the typescript and realtime functionality was the reason why I found your project. Previously I developed myself realtime layer above LB2 and I need to move it to the new generation and of course use typescript. So I see that I should wait until LB4 will be ready, to be sure that it is right way. And I agree that it will bring big changes but I hope that they will help build cleaner code.

Regards
AlesH

**Comment by jonathan-casarrubias** [comment] 2017-09-29 13:35
@aleho70 yes I know I had something promising with all the work I did to build FireLoop on top, but definitely LB4 changed everything, I still think I can rebuild on top of LB4, since I'm pretty sure they won't provide what we have here. But I definitely don't have the resources to maintain FireLoop for LB2~3 and a different one for LB4, so we will wait until LB4 is there.

If you already built a real-time layer you might want to collaborate on building the LB4 compatible version of the component realtime.

Cheers
Jon

**Comment by jonathan-casarrubias** [comment] 2018-02-10 18:29
Hi @aleho70 
Hey so, I really want to apologize for saying this but I'm stopping the support for FireLoop or any LoopBack module I built.

I'm working on a new project from scratch that of course is not built on top of LoopBack or anything else, this new project will also provide a SDK but now it won't be FrameWork specific, therefore you should be able to use it in Angular 5, React, Vue or even plain JavaScript projects


I apologize if you started a project on FireLoop, here I give a more detailed explanation:
https://github.com/mean-expert-official/fireloop.io/issues/137

**Closed as completed** 2018-02-10 18:28 UTC
Labels: question

**Comment by aleho70** [comment] 2018-02-10 20:36
Thank you for your message. I started to build my server also from scratch, based on microservices in typescript, currently above Nestjs with client side above ngrx. For realtime data synchronization layer between both I use some temporary solution above RethinkDB and I hope that I will replace it with something better later.
